# Generated by Django 3.1.7 on 2021-02-19 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pokemon',
            options={'verbose_name_plural': 'Pokemon'},
        ),
        migrations.AlterField(
            model_name='species',
            name='next_evolution',
            field=models.ForeignKey(default='N/A', on_delete=django.db.models.deletion.CASCADE, to='pokemon_app.species', verbose_name='Next Evolution'),
        ),
        migrations.AlterField(
            model_name='species',
            name='types',
            field=models.ManyToManyField(blank=True, to='pokemon_app.Type'),
        ),
    ]
