# Generated by Django 3.1.7 on 2021-02-19 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_app', '0002_auto_20210219_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='species',
            name='evolution_level',
            field=models.IntegerField(default='----', verbose_name='Evolution Level'),
        ),
        migrations.AlterField(
            model_name='species',
            name='name',
            field=models.CharField(default='----', max_length=20),
        ),
        migrations.AlterField(
            model_name='species',
            name='next_evolution',
            field=models.ForeignKey(default='----', on_delete=django.db.models.deletion.CASCADE, to='pokemon_app.species', verbose_name='Next Evolution'),
        ),
    ]
