# Generated by Django 3.1.7 on 2021-02-19 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_app', '0003_auto_20210219_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='species',
            name='next_evolution',
            field=models.ForeignKey(blank=True, default='----', null=True, on_delete=django.db.models.deletion.CASCADE, to='pokemon_app.species', verbose_name='Next Evolution'),
        ),
    ]
